### ISSUE TITLE
Totally gliched pdf frame on quark theme

### ISSUE THREAD

**Issue by XizzoR** [iusvar/grav-plugin-pdf-js#6]
Hello!

I just installed your plugin, enable it, put [pdfjs:mypdffilename.pdf] on page and run it in my browser. [It looks like this.](https://imgur.com/a/x6vvmif)

I use quark open publishing theme, page is using default template.

P.S. I can normally open this PDF file in my browser by routing to it.

**Comment by iusvar** [comment]
Hi, 

the filename is **mypdffilename.pdf** or **Ransomware Detection and Prevention.pdf** ?

if online, can you provide the address of the site?

**Comment by sunnyrs** [comment]
Hello,
I have the same problem in quark and learn2 theme.
[pdfjs file="e.pdf"/] and [pdfjs file=e.pdf/]
![image](https://user-images.githubusercontent.com/42800971/44779001-a35fe580-ab7e-11e8-8a80-d0d293dd58c0.png)
